### ISSUE TITLE
Small suggestions -typos

### ISSUE THREAD

**Issue by aedin** [bhklab/MetaGxBreast#1]
dupplicates    a list containing the names of patients that are believed to be dulicates across datasets  (Sp Duplicates)

loadBreastDatasets    Function to load breast cancer SummarizedExperiment objectsfrom the Experiment Hub  (Sp objectsfrom)

Vignettes Page2

Datasets: Retain studies with a minimum umber of genes (default = 0)   (Sp umber -> Number)

**Comment by ChristopherEeles** [comment]
These appear to have been corrected.

Feel free to open a new issue if you find any other typos.

Best,
Christopher Eeles
