### ISSUE TITLE
Error occurred: Query for the datasets embedded in MetaGxBreast R package

### ISSUE THREAD

**Issue by DongZhang94MD** [bhklab/MetaGxBreast#13]
Sorry for bother you.
       Recently, my friend and I have encountered an error when querying and downloading the public datasets curated in MetaGxBreast R package (as shown in attached screeshot). It seems that the public datasets with expression profiles and clinical data become unaccessible.
       We are wondering wether it is possible to solve this kind of problem.
       We are looking forward for your reply.
       Best wishes.
![WX20231009-002928@2x](https://github.com/bhklab/MetaGxBreast/assets/133837857/643b312e-2475-4aec-b9b0-2d1069767fa
![WechatIMG261](https://github.com/bhklab/MetaGxBreast/assets/133837857/5309aab6-53ac-4189-ab28-f14dc79461c1)
e)

**Comment by DongZhang94MD** [comment]
![WX20231009-002928@2x](https://github.com/bhklab/MetaGxBreast/assets/133837857/efe42a0b-dd46-4db9-825b-4783a380cadc)

**Comment by jjjermiah** [comment]
Hi there, 
Thanks for your issue. 
Could you please recreate the error and also upload your `sessionInfo()` output?

**Comment by DongZhang94MD** [comment]
Thanks for your help. We have check the r package in bioconductor and found the version has been updated in 2023-10-12. After updating our package, the problem has been resolved.



---- Replied Message ----
| From | Jermiah ***@***.***> |
| Date | 10/15/2023 00:56 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [bhklab/MetaGxBreast] Error occurred: Query for the datasets embedded in MetaGxBreast R package (Issue #13) |

Hi there,
Thanks for your issue.
Could you please recreate the error and also upload your sessionInfo() output?
