### ISSUE TITLE
could not find download options for TCGA and metabric.

### ISSUE THREAD

**Issue by wangt-biotime** [bhklab/MetaGxBreast#2]
How can we get TCGA and METABRIC datasets using MetaGxBreast?

**Comment by mzon7** [comment]
The datasets can be loaded together by using, breastEsets = loadBreastEsets(loadString = c("METABRIC", "TCGA")). Unfortunately the strings are case sensitive, I will try to remove this in a future update. I would recommend using allBreastData = loadBreastDatasets(). Esets are officially outdated objects and have been replaced by the summarizedExperiments object class. Plus the simple command loadBreastDatasets() will load in all of the data sets and then you can choose which ones to use once you have them all in your work space.
