### ISSUE TITLE
METABRIC data loading with MetaGxBreast

### ISSUE THREAD

**Issue by recpe** [bhklab/MetaGxBreast#8]
Hi Dr. Haibe-Kains,

I'm using the package MetaGxBreast to extract gene expression data from METABRIC and TCGA. However, it seems the function was not working recently for MetaGxBreast (error message attached).

Would you please help to solve this issue?

Thank you!

> library(MetaGxBreast)
> esets = MetaGxBreast::loadBreastEsets(loadString = c("TCGA","METABRIC"))[[1]]
snapshotDate(): 2021-10-19
see ?MetaGxBreast and browseVignettes('MetaGxBreast') for documentation
loading from cache
see ?MetaGxBreast and browseVignettes('MetaGxBreast') for documentation
loading from cache
Error: failed to load resource
  name: EH1099
  title: METABRIC
  reason: error in evaluating the argument 'x' in selecting a method for function 'get': bad restore file magic number (file may be corrupted) -- no data loaded
In addition: Warning message:
file ‘4e9e48f5de98_1099’ has magic number 'SQLit'
  Use of save versions prior to 2 is deprecated

**Comment by ChristopherEeles** [comment]
Hi @recpe,

It looks like the file is corrupted in your `ExperimentHub` cache, and thus can't be loaded into R. You can fix this by deleting the offending files in your cache.

You can find the path of your cache using:
```r
ExperimentHub::getExperimentHubOption("CACHE")
```

Then you will want to remove the file specified in the error message: `4e9e48f5de98_1099`. If you don't have other files in your cache you could also just delete the whole folder, but this would get rid of any other datasets you have in the cache as well.

Best,
Christopher Eeles
Software Developer
Haibe-Kains Lab
PM-Research | UHN

**Comment by ChristopherEeles** [comment]
If this hasn't solved your problem please feel free to message here again.
